/**
 * Back Office API
 * # Back Office For this system, a document is anything that has an id, a snippet, and an arbitrary set of properties. The id uniquely identifies the document in the system. The system uses the snippet to create a document representation that can be matched against user interests.  It is possible to attach any properties to a document; the system will not use them but will be returned together with the document when asking for personalized documents for a user. They could help store information like a title and the URL where it is possible to find the document. Each document can have its own set of properties.  The API offers an endpoint that allows uploading the documents to the system. After a successful upload, it will be possible to use the document in other endpoints.  # Auth To authenticate with the API, a token will be provided.
 *
 * The version of the OpenAPI document: 1.0.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DeleteDocumentsRequest from '../model/DeleteDocumentsRequest';
import DocumentPropertiesRequest from '../model/DocumentPropertiesRequest';
import DocumentPropertiesResponse from '../model/DocumentPropertiesResponse';
import DocumentPropertyRequest from '../model/DocumentPropertyRequest';
import DocumentPropertyResponse from '../model/DocumentPropertyResponse';
import GenericError from '../model/GenericError';
import IngestionError from '../model/IngestionError';
import IngestionRequest from '../model/IngestionRequest';

/**
* BackOffice service.
* @module com.xayn.backoffice/BackOfficeApi
* @version 1.0.15
*/
export default class BackOfficeApi {

    /**
    * Constructs a new BackOfficeApi. 
    * @alias module:com.xayn.backoffice/BackOfficeApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Add documents to the system
     * Add documents to the system. The system will create a representation of the document that will be used to match it against the preferences of a user.
     * @param {module:model/IngestionRequest} ingestionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    createDocumentsWithHttpInfo(ingestionRequest) {
      let postBody = ingestionRequest;
      // verify the required parameter 'ingestionRequest' is set
      if (ingestionRequest === undefined || ingestionRequest === null) {
        throw new Error("Missing the required parameter 'ingestionRequest' when calling createDocuments");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/documents', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Add documents to the system
     * Add documents to the system. The system will create a representation of the document that will be used to match it against the preferences of a user.
     * @param {module:model/IngestionRequest} ingestionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    createDocuments(ingestionRequest) {
      return this.createDocumentsWithHttpInfo(ingestionRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete the document from the system.
     * Permanently deletes the document from the system. The endpoint is idempotent. Deleting a non-existing document does not produce an error.
     * @param {String} documentId Id of the document
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteDocumentWithHttpInfo(documentId) {
      let postBody = null;
      // verify the required parameter 'documentId' is set
      if (documentId === undefined || documentId === null) {
        throw new Error("Missing the required parameter 'documentId' when calling deleteDocument");
      }

      let pathParams = {
        'document_id': documentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/documents/{document_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete the document from the system.
     * Permanently deletes the document from the system. The endpoint is idempotent. Deleting a non-existing document does not produce an error.
     * @param {String} documentId Id of the document
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteDocument(documentId) {
      return this.deleteDocumentWithHttpInfo(documentId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete all document properties
     * Deletes all the properties of the document.
     * @param {String} documentId Id of the document
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteDocumentPropertiesWithHttpInfo(documentId) {
      let postBody = null;
      // verify the required parameter 'documentId' is set
      if (documentId === undefined || documentId === null) {
        throw new Error("Missing the required parameter 'documentId' when calling deleteDocumentProperties");
      }

      let pathParams = {
        'document_id': documentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/documents/{document_id}/properties', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete all document properties
     * Deletes all the properties of the document.
     * @param {String} documentId Id of the document
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteDocumentProperties(documentId) {
      return this.deleteDocumentPropertiesWithHttpInfo(documentId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete a document property
     * Deletes the property of the document.
     * @param {String} documentId Id of the document
     * @param {String} propertyId Id of the document property
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteDocumentPropertyWithHttpInfo(documentId, propertyId) {
      let postBody = null;
      // verify the required parameter 'documentId' is set
      if (documentId === undefined || documentId === null) {
        throw new Error("Missing the required parameter 'documentId' when calling deleteDocumentProperty");
      }
      // verify the required parameter 'propertyId' is set
      if (propertyId === undefined || propertyId === null) {
        throw new Error("Missing the required parameter 'propertyId' when calling deleteDocumentProperty");
      }

      let pathParams = {
        'document_id': documentId,
        'property_id': propertyId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/documents/{document_id}/properties/{property_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete a document property
     * Deletes the property of the document.
     * @param {String} documentId Id of the document
     * @param {String} propertyId Id of the document property
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteDocumentProperty(documentId, propertyId) {
      return this.deleteDocumentPropertyWithHttpInfo(documentId, propertyId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete all listed documents.
     * Delete all documents listed in the request body. The endpoint is idempotent. I.e. if the list contains one or multiple non-existing documents, no error is produced.
     * @param {module:model/DeleteDocumentsRequest} deleteDocumentsRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteDocumentsWithHttpInfo(deleteDocumentsRequest) {
      let postBody = deleteDocumentsRequest;
      // verify the required parameter 'deleteDocumentsRequest' is set
      if (deleteDocumentsRequest === undefined || deleteDocumentsRequest === null) {
        throw new Error("Missing the required parameter 'deleteDocumentsRequest' when calling deleteDocuments");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/documents', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete all listed documents.
     * Delete all documents listed in the request body. The endpoint is idempotent. I.e. if the list contains one or multiple non-existing documents, no error is produced.
     * @param {module:model/DeleteDocumentsRequest} deleteDocumentsRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteDocuments(deleteDocumentsRequest) {
      return this.deleteDocumentsWithHttpInfo(deleteDocumentsRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a document property
     * Gets the property of the document.
     * @param {String} documentId Id of the document
     * @param {String} propertyId Id of the document property
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/DocumentPropertyResponse} and HTTP response
     */
    getDocumentPropertyWithHttpInfo(documentId, propertyId) {
      let postBody = null;
      // verify the required parameter 'documentId' is set
      if (documentId === undefined || documentId === null) {
        throw new Error("Missing the required parameter 'documentId' when calling getDocumentProperty");
      }
      // verify the required parameter 'propertyId' is set
      if (propertyId === undefined || propertyId === null) {
        throw new Error("Missing the required parameter 'propertyId' when calling getDocumentProperty");
      }

      let pathParams = {
        'document_id': documentId,
        'property_id': propertyId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DocumentPropertyResponse;
      return this.apiClient.callApi(
        '/documents/{document_id}/properties/{property_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get a document property
     * Gets the property of the document.
     * @param {String} documentId Id of the document
     * @param {String} propertyId Id of the document property
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/DocumentPropertyResponse}
     */
    getDocumentProperty(documentId, propertyId) {
      return this.getDocumentPropertyWithHttpInfo(documentId, propertyId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get all document properties
     * Gets all the properties of the document.
     * @param {String} documentId Id of the document
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/DocumentPropertiesResponse} and HTTP response
     */
    listDocumentPropertiesWithHttpInfo(documentId) {
      let postBody = null;
      // verify the required parameter 'documentId' is set
      if (documentId === undefined || documentId === null) {
        throw new Error("Missing the required parameter 'documentId' when calling listDocumentProperties");
      }

      let pathParams = {
        'document_id': documentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DocumentPropertiesResponse;
      return this.apiClient.callApi(
        '/documents/{document_id}/properties', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get all document properties
     * Gets all the properties of the document.
     * @param {String} documentId Id of the document
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/DocumentPropertiesResponse}
     */
    listDocumentProperties(documentId) {
      return this.listDocumentPropertiesWithHttpInfo(documentId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Set all document properties
     * Sets or replaces all the properties of the document.
     * @param {String} documentId Id of the document
     * @param {module:model/DocumentPropertiesRequest} documentPropertiesRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    replaceDocumentPropertiesWithHttpInfo(documentId, documentPropertiesRequest) {
      let postBody = documentPropertiesRequest;
      // verify the required parameter 'documentId' is set
      if (documentId === undefined || documentId === null) {
        throw new Error("Missing the required parameter 'documentId' when calling replaceDocumentProperties");
      }
      // verify the required parameter 'documentPropertiesRequest' is set
      if (documentPropertiesRequest === undefined || documentPropertiesRequest === null) {
        throw new Error("Missing the required parameter 'documentPropertiesRequest' when calling replaceDocumentProperties");
      }

      let pathParams = {
        'document_id': documentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/documents/{document_id}/properties', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Set all document properties
     * Sets or replaces all the properties of the document.
     * @param {String} documentId Id of the document
     * @param {module:model/DocumentPropertiesRequest} documentPropertiesRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    replaceDocumentProperties(documentId, documentPropertiesRequest) {
      return this.replaceDocumentPropertiesWithHttpInfo(documentId, documentPropertiesRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Set a document property
     * Sets or replaces the property of the document.
     * @param {String} documentId Id of the document
     * @param {String} propertyId Id of the document property
     * @param {module:model/DocumentPropertyRequest} documentPropertyRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    replaceDocumentPropertyWithHttpInfo(documentId, propertyId, documentPropertyRequest) {
      let postBody = documentPropertyRequest;
      // verify the required parameter 'documentId' is set
      if (documentId === undefined || documentId === null) {
        throw new Error("Missing the required parameter 'documentId' when calling replaceDocumentProperty");
      }
      // verify the required parameter 'propertyId' is set
      if (propertyId === undefined || propertyId === null) {
        throw new Error("Missing the required parameter 'propertyId' when calling replaceDocumentProperty");
      }
      // verify the required parameter 'documentPropertyRequest' is set
      if (documentPropertyRequest === undefined || documentPropertyRequest === null) {
        throw new Error("Missing the required parameter 'documentPropertyRequest' when calling replaceDocumentProperty");
      }

      let pathParams = {
        'document_id': documentId,
        'property_id': propertyId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/documents/{document_id}/properties/{property_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Set a document property
     * Sets or replaces the property of the document.
     * @param {String} documentId Id of the document
     * @param {String} propertyId Id of the document property
     * @param {module:model/DocumentPropertyRequest} documentPropertyRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    replaceDocumentProperty(documentId, propertyId, documentPropertyRequest) {
      return this.replaceDocumentPropertyWithHttpInfo(documentId, propertyId, documentPropertyRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
